name = "usketch-server"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[vars]
WEB_URL = "https://usketch-web.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "usketch-db"
database_id = "2a61b7ae-f239-4caf-a34c-357ad1ad49d9"

[durable_objects]
bindings = [
	{ name = "BOARD_ROOM", class_name = "BoardRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BoardRoom"]
